# Base configs
baseurl: "https://gchure.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-109526846-3" 

# UI configs
title: "Photography by Griffin Chure"
author: "Griffin Chure"
header:
 title: "Photography"
 subtitle: "by Griffin Chure"
footer:
bio: 
  I'm a biologist masquerading as a biophysicist who sometimes does art of
  various kinds. See my <a
  href="https://www.gchure.github.io"'> personal website</a> for the science
  stuff. Interested in using one of my photos for your project? Contact <a
  href="mailto:griffinchure@gmail.com"> griffinchure@gmail.com</a> for licensing
  information.
#  github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  twitter: "https://www.twitter.com/gdchure"
  instagram: "https://www.instagram.com/gchure"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/gchure"
